export const REGION_OPTIONS = [
  "Analamanga",
  "Bongolava",
  "Itasy",
  "Vakinankaratra",
  "Diana",
  "Sava",
  "Amoron'i Mania",
  "Atsimo-Atsinanana",
  "Fitovinany",
  "Matsiatra Ambony",
  "Ihorombe",
  "Vatovavy",
  "Betsiboka",
  "Boeny",
  "Melaky",
  "Sofia",
  "Alaotra-Mangoro",
  "Ambatosoa",
  "Analanjirofo",
  "Atsinanana",
  "Androy",
  "Anosy",
  "Atsimo-Andrefana",
  "Menabe",
] as const;

export const CITY_OPTIONS_BY_REGION: Record<string, string[]> = {
  Analamanga: [
    "Antananarivo-Renivohitra",
    "Ambohidratrimo",
    "Andramasina",
    "Anjozorobe",
    "Ankazobe",
    "Antananarivo-Atsimondrano",
    "Antananarivo-Avaradrano",
    "Manjakandriana",
  ],
  Bongolava: ["Tsiroanomandidy", "Fenoarivobe"],
  Itasy: ["Miarinarivo", "Arivonimamo", "Soavinandriana"],
  Vakinankaratra: ["Antsirabe", "Ambatolampy", "Antanifotsy", "Betafo", "Faratsiho"],
  Diana: ["Antsiranana", "Ambanja", "Ambilobe", "Nosy Be"],
  Sava: ["Sambava", "Antalaha", "Vohémar", "Andapa"],
  "Amoron'i Mania": ["Ambositra", "Fandriana", "Manandriana", "Ambatofinandrahana"],
  "Atsimo-Atsinanana": ["Farafangana", "Vangaindrano", "Midongy-Atsimo", "Befotaka"],
  Fitovinany: ["Manakara", "Vohipeno", "Ikongo"],
  "Matsiatra Ambony": ["Fianarantsoa", "Ambalavao", "Ikalamavony", "Vohibato", "Lalangina", "Isandra", "Vohimarina"],
  Ihorombe: ["Ihosy", "Ivohibe", "Etrobeky"],
  Vatovavy: ["Mananjary", "Nosy Varika", "Ifanadiana"],
  Betsiboka: ["Maevatanàna", "Kandreho", "Tsaratanana"],
  Boeny: ["Mahajanga", "Ambato-Boeni", "Marovoay", "Mitsinjo", "Soalala"],
  Melaky: ["Maintirano", "Besalampy", "Antsalova", "Morafenobe", "Tambohorano"],
  Sofia: ["Antsohihy", "Bealanana", "Befandriana-Nord", "Mandritsara", "Mampikony", "Port-Bergé"],
  "Alaotra-Mangoro": ["Ambatondrazaka", "Moramanga", "Andilamena", "Anosibe An'ala", "Amparafaravola"],
  Ambatosoa: ["Maroantsetra", "Antalaha"],
  Analanjirofo: ["Fenoarivo-Atsinanana", "Sainte-Marie", "Maroantsetra", "Mananara-Nord", "Soanierana Ivongo", "Vavatenina"],
  Atsinanana: ["Toamasina", "Brickaville", "Mahanoro", "Vatomandry", "Marolambo", "Antanambao Manampotsy"],
  Androy: ["Ambovombe-Androy", "Tsihombe", "Beloha", "Bekily"],
  Anosy: ["Tôlanaro", "Amboasary-Atsimo", "Betroka"],
  "Atsimo-Andrefana": ["Toliara", "Betioky", "Sakaraha", "Morombe", "Beroroha", "Ampanihy", "Benenitra", "Anakao"],
  Menabe: ["Morondava", "Miandrivazo", "Mahabo", "Manja", "Belo sur Tsiribihina"],
};

export const ALL_CITY_OPTIONS = Object.values(CITY_OPTIONS_BY_REGION).flat();
